/// Release Notes 英中翻译器。
///
/// 对 GitHub Release 的更新说明进行本地化翻译。
/// 采用字典替换方式，处理常见的英文术语、短语和句子模式。
/// 技术术语（如 Vulkan, Vulkan, JIT, ASTC 等）保留原文。
class ReleaseNotesTranslator {
  ReleaseNotesTranslator._();

  /// 翻译 release notes。
  ///
  /// 如果输入为 null 或空，返回原值。
  /// 翻译是尽力而为的，无法翻译的部分保留原文。
  static String? translate(String? notes) {
    if (notes == null || notes.isEmpty) return notes;

    var result = notes;

    // 先处理完整句子/短语（按长度降序，避免短词替换破坏长句）
    for (final entry in _phraseTranslations) {
      result = result.replaceAllMapped(entry.key, (m) => entry.value);
    }

    // 再处理单词/术语
    for (final entry in _wordTranslations) {
      result = result.replaceAllMapped(entry.key, (m) => entry.value);
    }

    return result;
  }

  /// 常见短语翻译表（按长度降序排列，优先匹配长短语）。
  static final List<MapEntry<RegExp, String>> _phraseTranslations = [
    // 完整句子
    MapEntry(RegExp(r'breaking changes?', caseSensitive: false),
        '破坏性变更'),
    MapEntry(RegExp(r'bug fixes?\b', caseSensitive: false), '问题修复'),
    MapEntry(RegExp(r'bug ?fix', caseSensitive: false), '问题修复'),
    MapEntry(RegExp(r'performance improvements?', caseSensitive: false),
        '性能优化'),
    MapEntry(RegExp(r'performance improvements?', caseSensitive: false),
        '性能优化'),
    MapEntry(RegExp(r'various improvements?', caseSensitive: false),
        '多项改进'),
    MapEntry(RegExp(r'minor improvements?', caseSensitive: false),
        '小幅改进'),
    MapEntry(RegExp(r'minor fixes?', caseSensitive: false), '小幅修复'),
    MapEntry(RegExp(r'minor changes?', caseSensitive: false), '小幅变更'),
    MapEntry(RegExp(r'general improvements?', caseSensitive: false),
        '整体改进'),
    MapEntry(RegExp(r'stability improvements?', caseSensitive: false),
        '稳定性提升'),
    MapEntry(RegExp(r'crash fixes?', caseSensitive: false), '崩溃修复'),
    MapEntry(RegExp(r'crash fix', caseSensitive: false), '崩溃修复'),
    MapEntry(RegExp(r'fixed a crash', caseSensitive: false), '修复崩溃'),
    MapEntry(RegExp(r'fixed crash', caseSensitive: false), '修复崩溃'),
    MapEntry(RegExp(r'fixed an? issue', caseSensitive: false), '修复问题'),
    MapEntry(RegExp(r'fixed issue', caseSensitive: false), '修复问题'),
    MapEntry(RegExp(r'fix a crash', caseSensitive: false), '修复崩溃'),
    MapEntry(RegExp(r'fix crash', caseSensitive: false), '修复崩溃'),
    MapEntry(RegExp(r'fix an? issue', caseSensitive: false), '修复问题'),
    MapEntry(RegExp(r'fix issue', caseSensitive: false), '修复问题'),
    MapEntry(RegExp(r'added support for', caseSensitive: false),
        '新增支持：'),
    MapEntry(RegExp(r'add support for', caseSensitive: false), '新增支持：'),
    MapEntry(RegExp(r'added support', caseSensitive: false), '新增支持'),
    MapEntry(RegExp(r'add support', caseSensitive: false), '新增支持'),
    MapEntry(RegExp(r'initial support for', caseSensitive: false),
        '初步支持：'),
    MapEntry(RegExp(r'initial support', caseSensitive: false), '初步支持'),
    MapEntry(RegExp(r'experimental support', caseSensitive: false),
        '实验性支持'),
    MapEntry(RegExp(r'new feature', caseSensitive: false), '新功能'),
    MapEntry(RegExp(r'new features', caseSensitive: false), '新功能'),
    MapEntry(RegExp(r'known issues?', caseSensitive: false), '已知问题'),
    MapEntry(RegExp(r'other changes?', caseSensitive: false), '其他变更'),
    MapEntry(RegExp(r'misc changes?', caseSensitive: false), '杂项变更'),
    MapEntry(RegExp(r'miscellaneous', caseSensitive: false), '杂项'),
    MapEntry(RegExp(r'general fixes?', caseSensitive: false), '常规修复'),
    MapEntry(RegExp(r'various fixes?', caseSensitive: false), '多项修复'),
    MapEntry(RegExp(r'various changes?', caseSensitive: false), '多项变更'),
    MapEntry(RegExp(r'updated translations?', caseSensitive: false),
        '更新翻译'),
    MapEntry(RegExp(r'translation updates?', caseSensitive: false),
        '翻译更新'),
    MapEntry(RegExp(r'updated dependencies?', caseSensitive: false),
        '更新依赖'),
    MapEntry(RegExp(r'dependency updates?', caseSensitive: false),
        '依赖更新'),
    MapEntry(RegExp(r'build improvements?', caseSensitive: false),
        '构建改进'),
    MapEntry(RegExp(r'code cleanup', caseSensitive: false), '代码清理'),
    MapEntry(RegExp(r'code refactoring', caseSensitive: false), '代码重构'),
    MapEntry(RegExp(r'refactoring', caseSensitive: false), '重构'),
    MapEntry(RegExp(r'improved performance', caseSensitive: false),
        '提升性能'),
    MapEntry(RegExp(r'improve performance', caseSensitive: false),
        '提升性能'),
    MapEntry(RegExp(r'improved stability', caseSensitive: false),
        '提升稳定性'),
    MapEntry(RegExp(r'improve stability', caseSensitive: false),
        '提升稳定性'),
    MapEntry(RegExp(r'improved compatibility', caseSensitive: false),
        '提升兼容性'),
    MapEntry(RegExp(r'improve compatibility', caseSensitive: false),
        '提升兼容性'),
    MapEntry(RegExp(r'improved accuracy', caseSensitive: false),
        '提升精确度'),
    MapEntry(RegExp(r'improve accuracy', caseSensitive: false), '提升精确度'),
    MapEntry(RegExp(r'better performance', caseSensitive: false),
        '更好的性能'),
    MapEntry(RegExp(r'better compatibility', caseSensitive: false),
        '更好的兼容性'),
    MapEntry(RegExp(r'better accuracy', caseSensitive: false),
        '更好的精确度'),
    MapEntry(RegExp(r'better stability', caseSensitive: false),
        '更好的稳定性'),
    MapEntry(RegExp(r'memory leak', caseSensitive: false), '内存泄漏'),
    MapEntry(RegExp(r'memory usage', caseSensitive: false), '内存占用'),
    MapEntry(RegExp(r'reduce memory', caseSensitive: false), '减少内存'),
    MapEntry(RegExp(r'save state', caseSensitive: false), '存档'),
    MapEntry(RegExp(r'save states', caseSensitive: false), '存档'),
    MapEntry(RegExp(r'cheat codes?', caseSensitive: false), '金手指'),
    MapEntry(RegExp(r'controller support', caseSensitive: false),
        '手柄支持'),
    MapEntry(RegExp(r'controller mapping', caseSensitive: false),
        '手柄映射'),
    MapEntry(RegExp(r'touch controls?', caseSensitive: false), '触控'),
    MapEntry(RegExp(r'on-screen controls?', caseSensitive: false),
        '屏幕按键'),
    MapEntry(RegExp(r'audio fixes?', caseSensitive: false), '音频修复'),
    MapEntry(RegExp(r'audio improvements?', caseSensitive: false),
        '音频改进'),
    MapEntry(RegExp(r'video fixes?', caseSensitive: false), '视频修复'),
    MapEntry(RegExp(r'video improvements?', caseSensitive: false),
        '视频改进'),
    MapEntry(RegExp(r'graphical fixes?', caseSensitive: false), '图形修复'),
    MapEntry(RegExp(r'graphical improvements?', caseSensitive: false),
        '图形改进'),
    MapEntry(RegExp(r'graphics fixes?', caseSensitive: false), '图形修复'),
    MapEntry(RegExp(r'graphics improvements?', caseSensitive: false),
        '图形改进'),
    MapEntry(RegExp(r'rendering fixes?', caseSensitive: false), '渲染修复'),
    MapEntry(RegExp(r'rendering improvements?', caseSensitive: false),
        '渲染改进'),
    MapEntry(RegExp(r'ui improvements?', caseSensitive: false), '界面改进'),
    MapEntry(RegExp(r'ui fixes?', caseSensitive: false), '界面修复'),
    MapEntry(RegExp(r'ui changes?', caseSensitive: false), '界面变更'),
    MapEntry(RegExp(r'user interface', caseSensitive: false), '用户界面'),
    MapEntry(RegExp(r'game compatibility', caseSensitive: false),
        '游戏兼容性'),
    MapEntry(RegExp(r'compatibility list', caseSensitive: false),
        '兼容性列表'),
    MapEntry(RegExp(r'full screen', caseSensitive: false), '全屏'),
    MapEntry(RegExp(r'fullscreen', caseSensitive: false), '全屏'),
    MapEntry(RegExp(r'landscape mode', caseSensitive: false), '横屏模式'),
    MapEntry(RegExp(r'portrait mode', caseSensitive: false), '竖屏模式'),
    MapEntry(RegExp(r'dark theme', caseSensitive: false), '深色主题'),
    MapEntry(RegExp(r'dark mode', caseSensitive: false), '深色模式'),
    MapEntry(RegExp(r'light theme', caseSensitive: false), '浅色主题'),
    MapEntry(RegExp(r'light mode', caseSensitive: false), '浅色模式'),
    MapEntry(RegExp(r'theme support', caseSensitive: false), '主题支持'),
    MapEntry(RegExp(r'notification', caseSensitive: false), '通知'),
    MapEntry(RegExp(r'settings? menu', caseSensitive: false), '设置菜单'),
    MapEntry(RegExp(r'settings? page', caseSensitive: false), '设置页面'),
    MapEntry(RegExp(r'settings? screen', caseSensitive: false), '设置界面'),
    MapEntry(RegExp(r'android 1[0-9]', caseSensitive: false), 'Android'),
  ];

  /// 单词/术语翻译表。
  static final List<MapEntry<RegExp, String>> _wordTranslations = [
    // 动词
    MapEntry(RegExp(r'\bFixed\b'), '修复'),
    MapEntry(RegExp(r'\bFixes\b'), '修复'),
    MapEntry(RegExp(r'\bFix\b'), '修复'),
    MapEntry(RegExp(r'\bAdded\b'), '新增'),
    MapEntry(RegExp(r'\bAdd\b'), '添加'),
    MapEntry(RegExp(r'\bAdds\b'), '添加'),
    MapEntry(RegExp(r'\bUpdated\b'), '更新'),
    MapEntry(RegExp(r'\bUpdate\b'), '更新'),
    MapEntry(RegExp(r'\bUpdates\b'), '更新'),
    MapEntry(RegExp(r'\bImproved\b'), '改进'),
    MapEntry(RegExp(r'\bImprove\b'), '改进'),
    MapEntry(RegExp(r'\bImproves\b'), '改进'),
    MapEntry(RegExp(r'\bImprovement\b'), '改进'),
    MapEntry(RegExp(r'\bImprovements\b'), '改进'),
    MapEntry(RegExp(r'\bRemoved\b'), '移除'),
    MapEntry(RegExp(r'\bRemove\b'), '移除'),
    MapEntry(RegExp(r'\bRemoves\b'), '移除'),
    MapEntry(RegExp(r'\bReplaced\b'), '替换'),
    MapEntry(RegExp(r'\bReplace\b'), '替换'),
    MapEntry(RegExp(r'\bOptimized\b'), '优化'),
    MapEntry(RegExp(r'\bOptimize\b'), '优化'),
    MapEntry(RegExp(r'\bRefactored\b'), '重构'),
    MapEntry(RegExp(r'\bRefactor\b'), '重构'),
    MapEntry(RegExp(r'\bRewritten\b'), '重写'),
    MapEntry(RegExp(r'\bRewrite\b'), '重写'),
    MapEntry(RegExp(r'\bMigrated\b'), '迁移'),
    MapEntry(RegExp(r'\bMigrate\b'), '迁移'),
    MapEntry(RegExp(r'\bDeprecated\b'), '已弃用'),
    MapEntry(RegExp(r'\bRestored\b'), '恢复'),
    MapEntry(RegExp(r'\bRestore\b'), '恢复'),
    MapEntry(RegExp(r'\bEnabled\b'), '启用'),
    MapEntry(RegExp(r'\bEnable\b'), '启用'),
    MapEntry(RegExp(r'\bDisabled\b'), '禁用'),
    MapEntry(RegExp(r'\bDisable\b'), '禁用'),
    MapEntry(RegExp(r'\bSupported\b'), '支持'),
    MapEntry(RegExp(r'\bSupport\b'), '支持'),
    MapEntry(RegExp(r'\bSupports\b'), '支持'),

    // 名词
    MapEntry(RegExp(r'\bPerformance\b'), '性能'),
    MapEntry(RegExp(r'\bStability\b'), '稳定性'),
    MapEntry(RegExp(r'\bCompatibility\b'), '兼容性'),
    MapEntry(RegExp(r'\bAccuracy\b'), '精确度'),
    MapEntry(RegExp(r'\bCrash\b'), '崩溃'),
    MapEntry(RegExp(r'\bCrashes\b'), '崩溃'),
    MapEntry(RegExp(r'\bBug\b'), '问题'),
    MapEntry(RegExp(r'\bBugs\b'), '问题'),
    MapEntry(RegExp(r'\bIssue\b'), '问题'),
    MapEntry(RegExp(r'\bIssues\b'), '问题'),
    MapEntry(RegExp(r'\bFeature\b'), '功能'),
    MapEntry(RegExp(r'\bFeatures\b'), '功能'),
    MapEntry(RegExp(r'\bChange\b'), '变更'),
    MapEntry(RegExp(r'\bChanges\b'), '变更'),
    MapEntry(RegExp(r'\bRelease\b'), '版本'),
    MapEntry(RegExp(r'\bVersion\b'), '版本'),
    MapEntry(RegExp(r'\bBuild\b'), '构建'),
    MapEntry(RegExp(r'\bUpdate\b'), '更新'),
    MapEntry(RegExp(r'\bUpdates\b'), '更新'),
    MapEntry(RegExp(r'\bMemory\b'), '内存'),
    MapEntry(RegExp(r'\bAudio\b'), '音频'),
    MapEntry(RegExp(r'\bVideo\b'), '视频'),
    MapEntry(RegExp(r'\bGraphics\b'), '图形'),
    MapEntry(RegExp(r'\bRendering\b'), '渲染'),
    MapEntry(RegExp(r'\bShader\b'), '着色器'),
    MapEntry(RegExp(r'\bShaders\b'), '着色器'),
    MapEntry(RegExp(r'\bTexture\b'), '纹理'),
    MapEntry(RegExp(r'\bTextures\b'), '纹理'),
    MapEntry(RegExp(r'\bController\b'), '手柄'),
    MapEntry(RegExp(r'\bControllers\b'), '手柄'),
    MapEntry(RegExp(r'\bGamepad\b'), '手柄'),
    MapEntry(RegExp(r'\bTouch\b'), '触摸'),
    MapEntry(RegExp(r'\bScreen\b'), '屏幕'),
    MapEntry(RegExp(r'\bTheme\b'), '主题'),
    MapEntry(RegExp(r'\bUI\b'), '界面'),
    MapEntry(RegExp(r'\bMenu\b'), '菜单'),
    MapEntry(RegExp(r'\bSettings?\b'), '设置'),
    MapEntry(RegExp(r'\bNotification'), '通知'),
    MapEntry(RegExp(r'\bTranslation'), '翻译'),
    MapEntry(RegExp(r'\bDependencies?\b'), '依赖'),
    MapEntry(RegExp(r'\bCode\b'), '代码'),
    MapEntry(RegExp(r'\bFile\b'), '文件'),
    MapEntry(RegExp(r'\bFiles\b'), '文件'),
    MapEntry(RegExp(r'\bConfig\b'), '配置'),
    MapEntry(RegExp(r'\bConfiguration\b'), '配置'),
    MapEntry(RegExp(r'\bOption\b'), '选项'),
    MapEntry(RegExp(r'\bOptions\b'), '选项'),
    MapEntry(RegExp(r'\bSetting\b'), '设置项'),

    // 形容词
    MapEntry(RegExp(r'\bExperimental\b'), '实验性'),
    MapEntry(RegExp(r'\bStable\b'), '稳定'),
    MapEntry(RegExp(r'\bUnstable\b'), '不稳定'),
    MapEntry(RegExp(r'\bBeta\b'), '测试版'),
    MapEntry(RegExp(r'\bAlpha\b'), '内测版'),
    MapEntry(RegExp(r'\bMinor\b'), '小幅'),
    MapEntry(RegExp(r'\bMajor\b'), '重大'),
    MapEntry(RegExp(r'\bVarious\b'), '多项'),
    MapEntry(RegExp(r'\bGeneral\b'), '常规'),
    MapEntry(RegExp(r'\bMisc\b'), '杂项'),
    MapEntry(RegExp(r'\bInitial\b'), '初始'),
    MapEntry(RegExp(r'\bNew\b'), '新增'),
    MapEntry(RegExp(r'\bOld\b'), '旧'),
    MapEntry(RegExp(r'\bPrevious\b'), '之前'),
    MapEntry(RegExp(r'\bLatest\b'), '最新'),
    MapEntry(RegExp(r'\bCurrent\b'), '当前'),
    MapEntry(RegExp(r'\bFull\b'), '完整'),
    MapEntry(RegExp(r'\bPartial\b'), '部分'),
    MapEntry(RegExp(r'\bNative\b'), '原生'),
    MapEntry(RegExp(r'\bCustom\b'), '自定义'),
    MapEntry(RegExp(r'\bDefault\b'), '默认'),
    MapEntry(RegExp(r'\bOptional\b'), '可选'),
    MapEntry(RegExp(r'\bAutomatic\b'), '自动'),
    MapEntry(RegExp(r'\bManual\b'), '手动'),

    // 介词/连接词
    MapEntry(RegExp(r'\bfor\b'), '针对'),
    MapEntry(RegExp(r'\bwith\b'), '附带'),
    MapEntry(RegExp(r'\bwithout\b'), '不包含'),
    MapEntry(RegExp(r'\bwhen\b'), '当'),
    MapEntry(RegExp(r'\bwhile\b'), '在...时'),
    MapEntry(RegExp(r'\bduring\b'), '在...期间'),
    MapEntry(RegExp(r'\bafter\b'), '在...后'),
    MapEntry(RegExp(r'\bbefore\b'), '在...前'),
    MapEntry(RegExp(r'\bnow\b'), '现已'),
    MapEntry(RegExp(r'\bplease\b'), '请'),
    MapEntry(RegExp(r'\bnote\b'), '注意'),
    MapEntry(RegExp(r'\bwarning\b'), '警告'),
    MapEntry(RegExp(r'\bimportant\b'), '重要'),
  ];
}
