/// Release Notes 英中翻译器。
///
/// 对 GitHub Release 的更新说明进行本地化翻译。
/// 采用字典替换方式，处理常见的英文术语、短语和句子模式。
/// 技术术语（如 Vulkan, JIT, ASTC 等）保留原文。
class ReleaseNotesTranslator {
  ReleaseNotesTranslator._();

  /// 翻译 release notes。
  ///
  /// 如果输入为 null 或空，返回原值。
  /// 翻译是尽力而为的，无法翻译的部分保留原文。
  static String? translate(String? notes) {
    if (notes == null || notes.isEmpty) return notes;

    var result = notes;

    // 先处理完整句子/短语（按长度降序，避免短词替换破坏长句）
    for (final entry in _phraseTranslations) {
      result = result.replaceAllMapped(entry.key, (m) => entry.value);
    }

    // 再处理单词/术语
    for (final entry in _wordTranslations) {
      result = result.replaceAllMapped(entry.key, (m) => entry.value);
    }

    return result;
  }

  /// 常见短语翻译表（按长度降序排列，优先匹配长短语）。
  static final List<MapEntry<RegExp, String>> _phraseTranslations = [
    // 完整句子
    MapEntry(RegExp(r'breaking changes?', caseSensitive: false), '破坏性变更'),
    MapEntry(RegExp(r'bug fixes?\b', caseSensitive: false), '问题修复'),
    MapEntry(RegExp(r'bug ?fix', caseSensitive: false), '问题修复'),
    MapEntry(RegExp(r'performance improvements?', caseSensitive: false), '性能优化'),
    MapEntry(RegExp(r'various improvements?', caseSensitive: false), '多项改进'),
    MapEntry(RegExp(r'minor improvements?', caseSensitive: false), '小幅改进'),
    MapEntry(RegExp(r'minor fixes?', caseSensitive: false), '小幅修复'),
    MapEntry(RegExp(r'minor changes?', caseSensitive: false), '小幅变更'),
    MapEntry(RegExp(r'general improvements?', caseSensitive: false), '整体改进'),
    MapEntry(RegExp(r'stability improvements?', caseSensitive: false), '稳定性提升'),
    MapEntry(RegExp(r'crash fixes?', caseSensitive: false), '崩溃修复'),
    MapEntry(RegExp(r'crash fix', caseSensitive: false), '崩溃修复'),
    MapEntry(RegExp(r'fixed a crash', caseSensitive: false), '修复崩溃'),
    MapEntry(RegExp(r'fixed crash', caseSensitive: false), '修复崩溃'),
    MapEntry(RegExp(r'fixed an? issue', caseSensitive: false), '修复问题'),
    MapEntry(RegExp(r'fixed issue', caseSensitive: false), '修复问题'),
    MapEntry(RegExp(r'fix a crash', caseSensitive: false), '修复崩溃'),
    MapEntry(RegExp(r'fix crash', caseSensitive: false), '修复崩溃'),
    MapEntry(RegExp(r'fix an? issue', caseSensitive: false), '修复问题'),
    MapEntry(RegExp(r'fix issue', caseSensitive: false), '修复问题'),
    MapEntry(RegExp(r'added support for', caseSensitive: false), '新增支持：'),
    MapEntry(RegExp(r'add support for', caseSensitive: false), '新增支持：'),
    MapEntry(RegExp(r'added support', caseSensitive: false), '新增支持'),
    MapEntry(RegExp(r'add support', caseSensitive: false), '新增支持'),
    MapEntry(RegExp(r'initial support for', caseSensitive: false), '初步支持：'),
    MapEntry(RegExp(r'initial support', caseSensitive: false), '初步支持'),
    MapEntry(RegExp(r'experimental support', caseSensitive: false), '实验性支持'),
    MapEntry(RegExp(r'new features?', caseSensitive: false), '新功能'),
    MapEntry(RegExp(r'known issues?', caseSensitive: false), '已知问题'),
    MapEntry(RegExp(r'other changes?', caseSensitive: false), '其他变更'),
    MapEntry(RegExp(r'misc changes?', caseSensitive: false), '杂项变更'),
    MapEntry(RegExp(r'miscellaneous', caseSensitive: false), '杂项'),
    MapEntry(RegExp(r'general fixes?', caseSensitive: false), '常规修复'),
    MapEntry(RegExp(r'various fixes?', caseSensitive: false), '多项修复'),
    MapEntry(RegExp(r'various changes?', caseSensitive: false), '多项变更'),
    MapEntry(RegExp(r'updated translations?', caseSensitive: false), '更新翻译'),
    MapEntry(RegExp(r'translation updates?', caseSensitive: false), '翻译更新'),
    MapEntry(RegExp(r'updated dependencies?', caseSensitive: false), '更新依赖'),
    MapEntry(RegExp(r'dependency updates?', caseSensitive: false), '依赖更新'),
    MapEntry(RegExp(r'build improvements?', caseSensitive: false), '构建改进'),
    MapEntry(RegExp(r'code cleanup', caseSensitive: false), '代码清理'),
    MapEntry(RegExp(r'code refactoring', caseSensitive: false), '代码重构'),
    MapEntry(RegExp(r'refactoring', caseSensitive: false), '重构'),
    MapEntry(RegExp(r'improved performance', caseSensitive: false), '提升性能'),
    MapEntry(RegExp(r'improve performance', caseSensitive: false), '提升性能'),
    MapEntry(RegExp(r'improved stability', caseSensitive: false), '提升稳定性'),
    MapEntry(RegExp(r'improve stability', caseSensitive: false), '提升稳定性'),
    MapEntry(RegExp(r'improved compatibility', caseSensitive: false), '提升兼容性'),
    MapEntry(RegExp(r'improve compatibility', caseSensitive: false), '提升兼容性'),
    MapEntry(RegExp(r'improved accuracy', caseSensitive: false), '提升精确度'),
    MapEntry(RegExp(r'improve accuracy', caseSensitive: false), '提升精确度'),
    MapEntry(RegExp(r'better performance', caseSensitive: false), '更好的性能'),
    MapEntry(RegExp(r'better compatibility', caseSensitive: false), '更好的兼容性'),
    MapEntry(RegExp(r'better accuracy', caseSensitive: false), '更好的精确度'),
    MapEntry(RegExp(r'better stability', caseSensitive: false), '更好的稳定性'),
    MapEntry(RegExp(r'memory leak', caseSensitive: false), '内存泄漏'),
    MapEntry(RegExp(r'memory usage', caseSensitive: false), '内存占用'),
    MapEntry(RegExp(r'reduce memory', caseSensitive: false), '减少内存'),
    MapEntry(RegExp(r'save states?', caseSensitive: false), '存档'),
    MapEntry(RegExp(r'cheat codes?', caseSensitive: false), '金手指'),
    MapEntry(RegExp(r'controller support', caseSensitive: false), '手柄支持'),
    MapEntry(RegExp(r'controller mapping', caseSensitive: false), '手柄映射'),
    MapEntry(RegExp(r'touch controls?', caseSensitive: false), '触控'),
    MapEntry(RegExp(r'on-screen controls?', caseSensitive: false), '屏幕按键'),
    MapEntry(RegExp(r'audio fixes?', caseSensitive: false), '音频修复'),
    MapEntry(RegExp(r'audio improvements?', caseSensitive: false), '音频改进'),
    MapEntry(RegExp(r'video fixes?', caseSensitive: false), '视频修复'),
    MapEntry(RegExp(r'video improvements?', caseSensitive: false), '视频改进'),
    MapEntry(RegExp(r'graphical fixes?', caseSensitive: false), '图形修复'),
    MapEntry(RegExp(r'graphical improvements?', caseSensitive: false), '图形改进'),
    MapEntry(RegExp(r'graphics fixes?', caseSensitive: false), '图形修复'),
    MapEntry(RegExp(r'graphics improvements?', caseSensitive: false), '图形改进'),
    MapEntry(RegExp(r'rendering fixes?', caseSensitive: false), '渲染修复'),
    MapEntry(RegExp(r'rendering improvements?', caseSensitive: false), '渲染改进'),
    MapEntry(RegExp(r'ui improvements?', caseSensitive: false), '界面改进'),
    MapEntry(RegExp(r'ui fixes?', caseSensitive: false), '界面修复'),
    MapEntry(RegExp(r'ui changes?', caseSensitive: false), '界面变更'),
    MapEntry(RegExp(r'user interface', caseSensitive: false), '用户界面'),
    MapEntry(RegExp(r'game compatibility', caseSensitive: false), '游戏兼容性'),
    MapEntry(RegExp(r'compatibility list', caseSensitive: false), '兼容性列表'),
    MapEntry(RegExp(r'full screen', caseSensitive: false), '全屏'),
    MapEntry(RegExp(r'fullscreen', caseSensitive: false), '全屏'),
    MapEntry(RegExp(r'landscape mode', caseSensitive: false), '横屏模式'),
    MapEntry(RegExp(r'portrait mode', caseSensitive: false), '竖屏模式'),
    MapEntry(RegExp(r'dark theme', caseSensitive: false), '深色主题'),
    MapEntry(RegExp(r'dark mode', caseSensitive: false), '深色模式'),
    MapEntry(RegExp(r'light theme', caseSensitive: false), '浅色主题'),
    MapEntry(RegExp(r'light mode', caseSensitive: false), '浅色模式'),
    MapEntry(RegExp(r'theme support', caseSensitive: false), '主题支持'),
    MapEntry(RegExp(r'notification', caseSensitive: false), '通知'),
    MapEntry(RegExp(r'settings? menu', caseSensitive: false), '设置菜单'),
    MapEntry(RegExp(r'settings? page', caseSensitive: false), '设置页面'),
    MapEntry(RegExp(r'settings? screen', caseSensitive: false), '设置界面'),
    // 仅替换 android 单词本身（lookahead 保留后面的版本号，如 "Android 13"）
    MapEntry(RegExp(r'android (?=1[0-9]\b)', caseSensitive: false), 'Android '),
    // --- 模拟器更新日志常见短语 ---
    MapEntry(RegExp(r'major update', caseSensitive: false), '重大更新'),
    MapEntry(RegExp(r'minor update', caseSensitive: false), '小幅更新'),
    MapEntry(RegExp(r'emulator core', caseSensitive: false), '模拟器核心'),
    MapEntry(RegExp(r'cpu overhead', caseSensitive: false), 'CPU 开销'),
    MapEntry(RegExp(r'per[- ]game', caseSensitive: false), '逐游戏'),
    MapEntry(RegExp(r'frame pacing', caseSensitive: false), '帧步调'),
    MapEntry(RegExp(r'frame rate[s]?', caseSensitive: false), '帧率'),
    MapEntry(RegExp(r'120\s*hz', caseSensitive: false), '120Hz'),
    MapEntry(RegExp(r'60\s*hz', caseSensitive: false), '60Hz'),
    MapEntry(RegExp(r'aspect ratio', caseSensitive: false), '宽高比'),
    MapEntry(RegExp(r'letterbox(ing)?', caseSensitive: false), '黑边'),
    MapEntry(RegExp(r'black bar[s]?', caseSensitive: false), '黑边'),
    MapEntry(RegExp(r'validation error[s]?', caseSensitive: false), '验证错误'),
    MapEntry(RegExp(r'feedback[- ]loop', caseSensitive: false), '反馈循环'),
    MapEntry(RegExp(r'pipeline flag[s]?', caseSensitive: false), '管线标志'),
    MapEntry(RegExp(r'ambient (background )?music', caseSensitive: false), '环境背景音乐'),
    MapEntry(RegExp(r'pause menu', caseSensitive: false), '暂停菜单'),
    MapEntry(RegExp(r'in[- ]app', caseSensitive: false), '应用内'),
    MapEntry(RegExp(r'save slot[s]?', caseSensitive: false), '存档槽'),
    MapEntry(RegExp(r'fast forward', caseSensitive: false), '快进'),
    MapEntry(RegExp(r'rewind (?!to)', caseSensitive: false), '倒带'),
    MapEntry(RegExp(r'speed hack[s]?', caseSensitive: false), '速度 hack'),
    MapEntry(RegExp(r'game fix', caseSensitive: false), '游戏修复'),
    MapEntry(RegExp(r'widescreen hack', caseSensitive: false), '宽屏 hack'),
    MapEntry(RegExp(r'upscaling', caseSensitive: false), '分辨率提升'),
    MapEntry(RegExp(r'upscale', caseSensitive: false), '分辨率提升'),
    MapEntry(RegExp(r'internal resolution', caseSensitive: false), '内部分辨率'),
    MapEntry(RegExp(r'anisotropic filtering', caseSensitive: false), '各向异性过滤'),
    MapEntry(RegExp(r'texture filtering', caseSensitive: false), '纹理过滤'),
    MapEntry(RegExp(r'frame skip', caseSensitive: false), '跳帧'),
    MapEntry(RegExp(r'vsync', caseSensitive: false), '垂直同步'),
    MapEntry(RegExp(r'vulkan', caseSensitive: false), 'Vulkan'),
    MapEntry(RegExp(r'opengl', caseSensitive: false), 'OpenGL'),
    MapEntry(RegExp(r'metal (?!gear)', caseSensitive: false), 'Metal'),
    MapEntry(RegExp(r'direct3d|d3d', caseSensitive: false), 'Direct3D'),
    MapEntry(RegExp(r'jit recompiler', caseSensitive: false), 'JIT 重编译器'),
    MapEntry(RegExp(r'recompiler', caseSensitive: false), '重编译器'),
    MapEntry(RegExp(r'interpreter', caseSensitive: false), '解释器'),
    MapEntry(RegExp(r'bios', caseSensitive: false), 'BIOS'),
    MapEntry(RegExp(r'gamepad', caseSensitive: false), '手柄'),
    MapEntry(RegExp(r'on[- ]screen', caseSensitive: false), '屏幕'),
    MapEntry(RegExp(r'touchscreen', caseSensitive: false), '触摸屏'),
    MapEntry(RegExp(r'cheat[s]?', caseSensitive: false), '金手指'),
    MapEntry(RegExp(r'achievement[s]?', caseSensitive: false), '成就'),
    MapEntry(RegExp(r'netplay', caseSensitive: false), '联机'),
    MapEntry(RegExp(r'multiplayer', caseSensitive: false), '多人游戏'),
    MapEntry(RegExp(r'single player', caseSensitive: false), '单人游戏'),
    MapEntry(RegExp(r'hotkey', caseSensitive: false), '快捷键'),
    MapEntry(RegExp(r'shortcut[s]?', caseSensitive: false), '快捷方式'),
    MapEntry(RegExp(r'plugin[s]?', caseSensitive: false), '插件'),
    MapEntry(RegExp(r'overlay', caseSensitive: false), '叠加层'),
    MapEntry(RegExp(r'theme[s]?', caseSensitive: false), '主题'),
    MapEntry(RegExp(r'preset[s]?', caseSensitive: false), '预设'),
    MapEntry(RegExp(r'workaround', caseSensitive: false), '临时方案'),
    MapEntry(RegExp(r'regression[s]?', caseSensitive: false), '回退问题'),
    MapEntry(RegExp(r'bottleneck', caseSensitive: false), '瓶颈'),
    MapEntry(RegExp(r'overhead', caseSensitive: false), '开销'),
    MapEntry(RegExp(r'throughput', caseSensitive: false), '吞吐量'),
    MapEntry(RegExp(r'latency', caseSensitive: false), '延迟'),
    MapEntry(RegExp(r'input lag', caseSensitive: false), '输入延迟'),
    MapEntry(RegExp(r'stutter(ing)?', caseSensitive: false), '卡顿'),
    MapEntry(RegExp(r'tear(ing)?', caseSensitive: false), '画面撕裂'),
    MapEntry(RegExp(r'glitch(es)?', caseSensitive: false), '画面异常'),
    MapEntry(RegExp(r'flicker(ing)?', caseSensitive: false), '闪烁'),
    MapEntry(RegExp(r'corrupt(ed|ion)?', caseSensitive: false), '损坏'),
    MapEntry(RegExp(r'artifact[s]?', caseSensitive: false), '渲染错误'),
    MapEntry(RegExp(r'black screen', caseSensitive: false), '黑屏'),
    MapEntry(RegExp(r'white screen', caseSensitive: false), '白屏'),
    MapEntry(RegExp(r'freeze[s]?', caseSensitive: false), '卡死'),
    MapEntry(RegExp(r'hang(s|ing)?', caseSensitive: false), '挂起'),
    MapEntry(RegExp(r'desync', caseSensitive: false), '不同步'),
    MapEntry(RegExp(r'out of sync', caseSensitive: false), '不同步'),
    MapEntry(RegExp(r'crash(es|ed|ing)?', caseSensitive: false), '崩溃'),
    MapEntry(RegExp(r'softlock', caseSensitive: false), '软锁死'),
    MapEntry(RegExp(r'game list', caseSensitive: false), '游戏列表'),
    MapEntry(RegExp(r'scan(s|ning)?', caseSensitive: false), '扫描'),
    MapEntry(RegExp(r'import(s|ed|ing)?', caseSensitive: false), '导入'),
    MapEntry(RegExp(r'export(s|ed|ing)?', caseSensitive: false), '导出'),
    MapEntry(RegExp(r'backup', caseSensitive: false), '备份'),
    MapEntry(RegExp(r'restore(d)?', caseSensitive: false), '恢复'),
    MapEntry(RegExp(r'migrate(d)?', caseSensitive: false), '迁移'),
    MapEntry(RegExp(r'port(ed)?', caseSensitive: false), '移植'),
    MapEntry(RegExp(r'fork(ed)?', caseSensitive: false), '分叉'),
    MapEntry(RegExp(r'upstream', caseSensitive: false), '上游'),
    MapEntry(RegExp(r'downstream', caseSensitive: false), '下游'),
    MapEntry(RegExp(r'backend', caseSensitive: false), '后端'),
    MapEntry(RegExp(r'frontend', caseSensitive: false), '前端'),
    MapEntry(RegExp(r'sidebar', caseSensitive: false), '侧边栏'),
    MapEntry(RegExp(r'toolbar', caseSensitive: false), '工具栏'),
    MapEntry(RegExp(r'statusbar', caseSensitive: false), '状态栏'),
    MapEntry(RegExp(r'tab(s|bar)?', caseSensitive: false), '标签页'),
    MapEntry(RegExp(r'dropdown', caseSensitive: false), '下拉'),
    MapEntry(RegExp(r'checkbox(es)?', caseSensitive: false), '复选框'),
    MapEntry(RegExp(r'slider', caseSensitive: false), '滑块'),
    MapEntry(RegExp(r'toggle', caseSensitive: false), '开关'),
    MapEntry(RegExp(r'tooltip', caseSensitive: false), '提示'),
    MapEntry(RegExp(r'shortcut[s]?', caseSensitive: false), '快捷方式'),
    MapEntry(RegExp(r'gamepad', caseSensitive: false), '手柄'),
    MapEntry(RegExp(r'analog stick', caseSensitive: false), '摇杆'),
    MapEntry(RegExp(r'd[- ]pad', caseSensitive: false), '方向键'),
    MapEntry(RegExp(r'trigger[s]?', caseSensitive: false), '扳机键'),
    MapEntry(RegExp(r'bumper', caseSensitive: false), '肩键'),
    MapEntry(RegExp(r'haptic', caseSensitive: false), '触觉反馈'),
    MapEntry(RegExp(r'vibration', caseSensitive: false), '震动'),
    MapEntry(RegExp(r'rumble', caseSensitive: false), '震动'),
  ];

  /// 单词/术语翻译表。
  static final List<MapEntry<RegExp, String>> _wordTranslations = [
    // 动词
    MapEntry(RegExp(r'\bFixed\b', caseSensitive: false), '修复'),
    MapEntry(RegExp(r'\bFixes\b', caseSensitive: false), '修复'),
    MapEntry(RegExp(r'\bFix\b', caseSensitive: false), '修复'),
    MapEntry(RegExp(r'\bAdded\b', caseSensitive: false), '新增'),
    MapEntry(RegExp(r'\bAdd\b', caseSensitive: false), '添加'),
    MapEntry(RegExp(r'\bAdds\b', caseSensitive: false), '添加'),
    MapEntry(RegExp(r'\bUpdated\b', caseSensitive: false), '更新'),
    MapEntry(RegExp(r'\bUpdate\b', caseSensitive: false), '更新'),
    MapEntry(RegExp(r'\bUpdates\b', caseSensitive: false), '更新'),
    MapEntry(RegExp(r'\bImproved\b', caseSensitive: false), '改进'),
    MapEntry(RegExp(r'\bImprove\b', caseSensitive: false), '改进'),
    MapEntry(RegExp(r'\bImproves\b', caseSensitive: false), '改进'),
    MapEntry(RegExp(r'\bImprovement\b', caseSensitive: false), '改进'),
    MapEntry(RegExp(r'\bImprovements\b', caseSensitive: false), '改进'),
    MapEntry(RegExp(r'\bRemoved\b', caseSensitive: false), '移除'),
    MapEntry(RegExp(r'\bRemove\b', caseSensitive: false), '移除'),
    MapEntry(RegExp(r'\bRemoves\b', caseSensitive: false), '移除'),
    MapEntry(RegExp(r'\bReplaced\b', caseSensitive: false), '替换'),
    MapEntry(RegExp(r'\bReplace\b', caseSensitive: false), '替换'),
    MapEntry(RegExp(r'\bOptimized\b', caseSensitive: false), '优化'),
    MapEntry(RegExp(r'\bOptimize\b', caseSensitive: false), '优化'),
    MapEntry(RegExp(r'\bRefactored\b', caseSensitive: false), '重构'),
    MapEntry(RegExp(r'\bRefactor\b', caseSensitive: false), '重构'),
    MapEntry(RegExp(r'\bRewritten\b', caseSensitive: false), '重写'),
    MapEntry(RegExp(r'\bRewrite\b', caseSensitive: false), '重写'),
    MapEntry(RegExp(r'\bMigrated\b', caseSensitive: false), '迁移'),
    MapEntry(RegExp(r'\bMigrate\b', caseSensitive: false), '迁移'),
    MapEntry(RegExp(r'\bDeprecated\b', caseSensitive: false), '已弃用'),
    MapEntry(RegExp(r'\bRestored\b', caseSensitive: false), '恢复'),
    MapEntry(RegExp(r'\bRestore\b', caseSensitive: false), '恢复'),
    MapEntry(RegExp(r'\bEnabled\b', caseSensitive: false), '启用'),
    MapEntry(RegExp(r'\bEnable\b', caseSensitive: false), '启用'),
    MapEntry(RegExp(r'\bDisabled\b', caseSensitive: false), '禁用'),
    MapEntry(RegExp(r'\bDisable\b', caseSensitive: false), '禁用'),
    MapEntry(RegExp(r'\bSupported\b', caseSensitive: false), '支持'),
    MapEntry(RegExp(r'\bSupport\b', caseSensitive: false), '支持'),
    MapEntry(RegExp(r'\bSupports\b', caseSensitive: false), '支持'),

    // 名词
    MapEntry(RegExp(r'\bPerformance\b', caseSensitive: false), '性能'),
    MapEntry(RegExp(r'\bStability\b', caseSensitive: false), '稳定性'),
    MapEntry(RegExp(r'\bCompatibility\b', caseSensitive: false), '兼容性'),
    MapEntry(RegExp(r'\bAccuracy\b', caseSensitive: false), '精确度'),
    MapEntry(RegExp(r'\bCrash\b', caseSensitive: false), '崩溃'),
    MapEntry(RegExp(r'\bCrashes\b', caseSensitive: false), '崩溃'),
    MapEntry(RegExp(r'\bBug\b', caseSensitive: false), '问题'),
    MapEntry(RegExp(r'\bBugs\b', caseSensitive: false), '问题'),
    MapEntry(RegExp(r'\bIssue\b', caseSensitive: false), '问题'),
    MapEntry(RegExp(r'\bIssues\b', caseSensitive: false), '问题'),
    MapEntry(RegExp(r'\bFeature\b', caseSensitive: false), '功能'),
    MapEntry(RegExp(r'\bFeatures\b', caseSensitive: false), '功能'),
    MapEntry(RegExp(r'\bChange\b', caseSensitive: false), '变更'),
    MapEntry(RegExp(r'\bChanges\b', caseSensitive: false), '变更'),
    MapEntry(RegExp(r'\bRelease\b', caseSensitive: false), '版本'),
    MapEntry(RegExp(r'\bVersion\b', caseSensitive: false), '版本'),
    MapEntry(RegExp(r'\bBuild\b', caseSensitive: false), '构建'),
    MapEntry(RegExp(r'\bMemory\b', caseSensitive: false), '内存'),
    MapEntry(RegExp(r'\bAudio\b', caseSensitive: false), '音频'),
    MapEntry(RegExp(r'\bVideo\b', caseSensitive: false), '视频'),
    MapEntry(RegExp(r'\bGraphics\b', caseSensitive: false), '图形'),
    MapEntry(RegExp(r'\bRendering\b', caseSensitive: false), '渲染'),
    MapEntry(RegExp(r'\bShader\b', caseSensitive: false), '着色器'),
    MapEntry(RegExp(r'\bShaders\b', caseSensitive: false), '着色器'),
    MapEntry(RegExp(r'\bTexture\b', caseSensitive: false), '纹理'),
    MapEntry(RegExp(r'\bTextures\b', caseSensitive: false), '纹理'),
    MapEntry(RegExp(r'\bController\b', caseSensitive: false), '手柄'),
    MapEntry(RegExp(r'\bControllers\b', caseSensitive: false), '手柄'),
    MapEntry(RegExp(r'\bGamepad\b', caseSensitive: false), '手柄'),
    MapEntry(RegExp(r'\bTouch\b', caseSensitive: false), '触摸'),
    MapEntry(RegExp(r'\bScreen\b', caseSensitive: false), '屏幕'),
    MapEntry(RegExp(r'\bTheme\b', caseSensitive: false), '主题'),
    MapEntry(RegExp(r'\bUI\b', caseSensitive: false), '界面'),
    MapEntry(RegExp(r'\bMenu\b', caseSensitive: false), '菜单'),
    MapEntry(RegExp(r'\bSettings?\b', caseSensitive: false), '设置'),
    MapEntry(RegExp(r'\bNotification', caseSensitive: false), '通知'),
    MapEntry(RegExp(r'\bTranslation', caseSensitive: false), '翻译'),
    MapEntry(RegExp(r'\bDependencies?\b', caseSensitive: false), '依赖'),
    MapEntry(RegExp(r'\bCode\b', caseSensitive: false), '代码'),
    MapEntry(RegExp(r'\bFile\b', caseSensitive: false), '文件'),
    MapEntry(RegExp(r'\bFiles\b', caseSensitive: false), '文件'),
    MapEntry(RegExp(r'\bConfig\b', caseSensitive: false), '配置'),
    MapEntry(RegExp(r'\bConfiguration\b', caseSensitive: false), '配置'),
    MapEntry(RegExp(r'\bOption\b', caseSensitive: false), '选项'),
    MapEntry(RegExp(r'\bOptions\b', caseSensitive: false), '选项'),
    MapEntry(RegExp(r'\bSetting\b', caseSensitive: false), '设置项'),

    // 形容词
    MapEntry(RegExp(r'\bExperimental\b', caseSensitive: false), '实验性'),
    MapEntry(RegExp(r'\bStable\b', caseSensitive: false), '稳定'),
    MapEntry(RegExp(r'\bUnstable\b', caseSensitive: false), '不稳定'),
    MapEntry(RegExp(r'\bBeta\b', caseSensitive: false), '测试版'),
    MapEntry(RegExp(r'\bAlpha\b', caseSensitive: false), '内测版'),
    MapEntry(RegExp(r'\bMinor\b', caseSensitive: false), '小幅'),
    MapEntry(RegExp(r'\bMajor\b', caseSensitive: false), '重大'),
    MapEntry(RegExp(r'\bVarious\b', caseSensitive: false), '多项'),
    MapEntry(RegExp(r'\bGeneral\b', caseSensitive: false), '常规'),
    MapEntry(RegExp(r'\bMisc\b', caseSensitive: false), '杂项'),
    MapEntry(RegExp(r'\bInitial\b', caseSensitive: false), '初始'),
    MapEntry(RegExp(r'\bNew\b', caseSensitive: false), '新增'),
    MapEntry(RegExp(r'\bOld\b', caseSensitive: false), '旧'),
    MapEntry(RegExp(r'\bPrevious\b', caseSensitive: false), '之前'),
    MapEntry(RegExp(r'\bLatest\b', caseSensitive: false), '最新'),
    MapEntry(RegExp(r'\bCurrent\b', caseSensitive: false), '当前'),
    MapEntry(RegExp(r'\bFull\b', caseSensitive: false), '完整'),
    MapEntry(RegExp(r'\bPartial\b', caseSensitive: false), '部分'),
    MapEntry(RegExp(r'\bNative\b', caseSensitive: false), '原生'),
    MapEntry(RegExp(r'\bCustom\b', caseSensitive: false), '自定义'),
    MapEntry(RegExp(r'\bDefault\b', caseSensitive: false), '默认'),
    MapEntry(RegExp(r'\bOptional\b', caseSensitive: false), '可选'),
    MapEntry(RegExp(r'\bAutomatic\b', caseSensitive: false), '自动'),
    MapEntry(RegExp(r'\bManual\b', caseSensitive: false), '手动'),

    // 介词/连接词
    MapEntry(RegExp(r'\bfor\b', caseSensitive: false), '针对'),
    MapEntry(RegExp(r'\bwith\b', caseSensitive: false), '附带'),
    MapEntry(RegExp(r'\bwithout\b', caseSensitive: false), '不包含'),
    MapEntry(RegExp(r'\bwhen\b', caseSensitive: false), '当'),
    MapEntry(RegExp(r'\bwhile\b', caseSensitive: false), '在...时'),
    MapEntry(RegExp(r'\bduring\b', caseSensitive: false), '在...期间'),
    MapEntry(RegExp(r'\bafter\b', caseSensitive: false), '在...后'),
    MapEntry(RegExp(r'\bbefore\b', caseSensitive: false), '在...前'),
    MapEntry(RegExp(r'\bnow\b', caseSensitive: false), '现已'),
    MapEntry(RegExp(r'\bplease\b', caseSensitive: false), '请'),
    MapEntry(RegExp(r'\bnote\b', caseSensitive: false), '注意'),
    MapEntry(RegExp(r'\bwarning\b', caseSensitive: false), '警告'),
    MapEntry(RegExp(r'\bimportant\b', caseSensitive: false), '重要'),
  ];
}
