import 'dart:convert';

import 'package:dio/dio.dart';
import 'package:flutter/services.dart';

import '../../data/models/emulator.dart';
import '../../data/models/version_info.dart';

typedef VersionCatalogLoader = Future<Map<String, dynamic>> Function();

/// Loads the compact release snapshot generated by GitHub Actions.
///
/// A full mobile-side refresh previously downloaded hundreds of GitHub
/// Releases HTML pages. The catalog reduces that work to one small request and
/// already contains the release selected by the greatest `published_at` value.
/// If the remote file is temporarily unavailable, the catalog bundled in the
/// APK provides an immediate baseline and the normal source adapter remains the
/// final fallback.
class VersionCatalogService {
  VersionCatalogService({
    Dio? dio,
    AssetBundle? bundle,
    VersionCatalogLoader? loader,
    this.remoteUrl =
        'https://raw.githubusercontent.com/kongmao4567890-glitch/emuhub/main/data/version_catalog.json',
  })  : _dio = dio ??
            Dio(
              BaseOptions(
                connectTimeout: const Duration(seconds: 8),
                receiveTimeout: const Duration(seconds: 8),
                headers: const {
                  'Accept': 'application/json',
                  'User-Agent':
                      'EmuHub/1.0 (+https://github.com/kongmao4567890-glitch/emuhub)',
                },
              ),
            ),
        _bundle = bundle ?? rootBundle,
        _loader = loader;

  static const Duration _memoryTtl = Duration(minutes: 15);

  final Dio _dio;
  final AssetBundle _bundle;
  final VersionCatalogLoader? _loader;
  final String remoteUrl;

  Future<Map<String, dynamic>>? _inFlight;
  DateTime? _loadedAt;

  /// Returns a release entry for [emulator], or null when it is not represented
  /// in the catalog. Callers should then use the regular source adapter.
  Future<VersionInfo?> lookup(Emulator emulator) async {
    final catalog = await _catalog();
    final entries = _asMap(catalog['entries']);
    final entry = _asMap(entries[emulator.id]);
    final version = entry['version']?.toString().trim() ?? '';
    if (version.isEmpty) return null;

    return VersionInfo(
      emulatorId: emulator.id,
      version: version,
      releaseDate: _parseDate(entry['releaseDate']),
      releaseNotes: _nonEmpty(entry['releaseNotes']),
      isNew: false,
      downloadUrl: _nonEmpty(entry['downloadUrl']),
      devDownloadUrl: _nonEmpty(entry['devDownloadUrl']),
      devReleaseNotes: _nonEmpty(entry['devReleaseNotes']),
    );
  }

  /// Emulator ids that can be served without a per-repository request.
  ///
  /// UpdateService uses this to process catalog hits before slower fallback
  /// sources, so missing legacy repositories cannot hold up visible results.
  Future<Set<String>> availableEmulatorIds() async {
    final catalog = await _catalog();
    return _asMap(catalog['entries']).keys.toSet();
  }

  Future<Map<String, dynamic>> _catalog() {
    final now = DateTime.now();
    final loadedAt = _loadedAt;
    if (_inFlight != null &&
        loadedAt != null &&
        now.difference(loadedAt) < _memoryTtl) {
      return _inFlight!;
    }

    _loadedAt = now;
    return _inFlight = _loadCatalog();
  }

  Future<Map<String, dynamic>> _loadCatalog() async {
    if (_loader != null) return _loader!();

    try {
      // A small time bucket bypasses stale intermediary caches without causing
      // every item lookup to download the file again.
      final bucket = DateTime.now().millisecondsSinceEpoch ~/
          _memoryTtl.inMilliseconds;
      final response = await _dio.get<dynamic>('$remoteUrl?catalog=$bucket');
      final parsed = _decode(response.data);
      if (_hasEntries(parsed)) return parsed;
    } catch (_) {
      // Offline, captive portal, or raw.githubusercontent.com unavailable.
    }

    try {
      final raw = await _bundle.loadString('assets/version_catalog.json');
      final parsed = _decode(raw);
      if (_hasEntries(parsed)) return parsed;
    } catch (_) {
      // The source adapter will provide the final fallback.
    }
    return <String, dynamic>{};
  }

  bool _hasEntries(Map<String, dynamic> value) =>
      _asMap(value['entries']).isNotEmpty;

  Map<String, dynamic> _decode(dynamic value) {
    if (value is Map<String, dynamic>) return value;
    if (value is Map) return Map<String, dynamic>.from(value);
    if (value is String && value.isNotEmpty) {
      try {
        final decoded = jsonDecode(value);
        if (decoded is Map) return Map<String, dynamic>.from(decoded);
      } catch (_) {}
    }
    return <String, dynamic>{};
  }

  Map<String, dynamic> _asMap(dynamic value) {
    if (value is Map<String, dynamic>) return value;
    if (value is Map) return Map<String, dynamic>.from(value);
    return <String, dynamic>{};
  }

  DateTime? _parseDate(dynamic value) {
    final raw = value?.toString();
    if (raw == null || raw.isEmpty) return null;
    return DateTime.tryParse(raw);
  }

  String? _nonEmpty(dynamic value) {
    final text = value?.toString().trim();
    return text == null || text.isEmpty ? null : text;
  }
}
